set serveroutput on 

declare
json_body_blob  blob;
json_body_clob  clob;
 function conv_json_request_blob2clob (json_body_blob in blob) return clob as
   json_body_clob clob;
   v_dest_offset pls_integer := 1;
   v_src_offset pls_integer := 1;
   v_lang_context pls_integer := dbms_lob.default_lang_ctx;
   v_warning pls_integer;
   begin
     if json_body_blob is not null then
       if length(json_body_blob) = 0 then
          return empty_clob();
       end if;
       dbms_lob.createtemporary(lob_loc => json_body_clob,
       cache => true); -- read into buffer cache
       dbms_lob.converttoclob(
                            dest_lob => json_body_clob,
                            src_blob => json_body_blob,
                            amount => dbms_lob.lobmaxsize,
                            dest_offset => v_dest_offset,
                            src_offset => v_src_offset,
                            blob_csid => dbms_lob.default_csid,
                            lang_context => v_lang_context,
                            warning => v_warning
                             );
     else
      json_body_clob := null;
     end if;
     return json_body_clob;
  exception
    when others then
    json_body_clob := null;
  end conv_json_request_blob2clob;

begin
json_body_blob:= utl_raw.cast_to_raw('{
   "pending_payments":[
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       },
       {
          "payment_processing_ref":"PPRTC33"
       }
   ]
}');
json_body_clob:=conv_json_request_blob2clob(json_body_blob);
dbms_output.put_line(json_body_clob);
end;
